### ISSUE TITLE
undefined method `visit_each' on array(:integer) with XOR

### ISSUE THREAD

**Issue by ndan** [dry-rb/dry-schema#138]
Method `Dry::Schema::Result#errors` raises an error when using `array(...)` with XOR predicate.

```ruby
schema = Dry::Schema.Params do
  required(:ids) do
    array(:integer) ^ eql?([''])
  end
end

schema.call(ids: 'asdf').errors
Traceback (most recent call last):
       16: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       15: from (irb):386
       14: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/result.rb:113:in `errors'
       13: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/result.rb:127:in `message_set'
       12: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:66:in `call'
       11: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:66:in `map'
       10: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:66:in `block in call'
        9: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:73:in `visit'
        8: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:150:in `visit_key'
        7: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:73:in `visit'
        6: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:167:in `visit_xor'
        5: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:73:in `visit'
        4: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:94:in `visit_and'
        3: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:94:in `map'
        2: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:94:in `block in visit_and'
        1: from /Users/daniil/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/message_compiler.rb:73:in `visit'
NoMethodError (undefined method `visit_each' for #<Dry::Schema::MessageCompiler:0x00007fc6081217b0>)
```

ps. Disjunction (OR) works fine

**Comment by solnic** [comment]
This should not crash of course, but I also wanted to point out that you want to use a custom type that will reject blank strings and return an empty array, rather than defining complex validations.
