### ISSUE TITLE
Message generator chokes on processing disjunction

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-schema#26]
Taken from https://github.com/dry-rb/dry-validation/issues/280
```ruby
(Dry::Schema.define { required(:foo) { str? & filled? | int? } }).call({}).messages

Traceback (most recent call last):
        17: from ./bin/console:40:in `<main>'
        16: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/result.rb:117:in `messages'
        15: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/result.rb:142:in `message_set'
        14: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:45:in `call'
        13: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:45:in `map'
        12: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:45:in `block in call'
        11: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:50:in `visit'
        10: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:79:in `visit_and'
         9: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:79:in `map'
         8: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:79:in `block in visit_and'
         7: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:50:in `visit'
         6: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:62:in `visit_hint'
         5: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:50:in `visit'
         4: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:137:in `visit_key'
         3: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:50:in `visit'
         2: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:93:in `visit_or'
         1: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:93:in `new'

```

**Comment by flash-gordon** [comment]
This is another one

```ruby
schema = Dry::Schema.define do
  required(:attributes).schema do
    optional(:text) { int? | nil? }
  end
end

schema.({}).messages

         9: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/result.rb:117:in `messages'
         8: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/result.rb:142:in `message_set'
         7: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_compiler.rb:45:in `call'
         6: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_set.rb:22:in `[]'
         5: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_set.rb:22:in `new'
         4: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_set.rb:34:in `initialize'
         3: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_set.rb:107:in `initialize_placeholders!'
         2: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_set.rb:107:in `reduce'
         1: from /Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_set.rb:107:in `each'
/Users/gordon/dev/dry-rb/dry-schema/lib/dry/schema/message_set.rb:114:in `block in initialize_placeholders!': no implicit conversion of Symbol into Integer (TypeError)
```

**Comment by aleksandra-stolyar** [comment]
ran into this issue using dry-validation.
`NoMethodError: undefined method 'path' for #<Dry::Schema::Message::Or::MultiPath:0x0000557e8515bcc0>
from /usr/local/bundle/gems/dry-schema-1.6.2/lib/dry/schema/result.rb:115:in 'block in error?'`

my schema:
```
EmailType = Dry::Schema.Params do
  ....
end

NicknameType = Dry::Schema.Params do
  required(:nickname).filled(:string, max_size?: 200)
  required(:password).filled(:string, min_size?: 8, max_size?: 128)
end

class SomeContract
  params do
    required(:creds).hash(EmailType | NicknameType)
  end
end
```

tried to pass only `nickname` without `password` and got this error
```
contract = SomeContract.new
contract.call(input)
```
